# Generated by Django 5.0 on 2023-12-07 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('doamin', models.CharField(max_length=100)),
                ('record', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('doamin', models.CharField(max_length=100)),
                ('record', models.CharField(max_length=10)),
                ('res_type', models.CharField(max_length=10)),
                ('delay', models.FloatField()),
                ('TSIG', models.FloatField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.query')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reply')),
            ],
        ),
    ]
