# Generated by Django 5.0 on 2023-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DNSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField()),
                ('domain_name', models.CharField(max_length=255)),
                ('record_type', models.CharField(max_length=10)),
                ('query_class', models.CharField(max_length=10)),
                ('query_type', models.CharField(max_length=10)),
                ('query_time', models.FloatField()),
                ('num_records', models.IntegerField()),
                ('record_size', models.IntegerField()),
                ('latitude', models.CharField(blank='', default='', max_length=200)),
                ('longitude', models.CharField(blank='', default='', max_length=200)),
            ],
        ),
    ]
