# Generated by Django 5.0 on 2023-12-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='doamin',
            new_name='domain',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='doamin',
            new_name='domain',
        ),
    ]
