# Generated by Django 5.0 on 2023-12-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('process', models.CharField(max_length=50)),
                ('query_ip', models.GenericIPAddressField()),
                ('query_domain', models.CharField(max_length=255)),
                ('record_type', models.CharField(max_length=5)),
                ('response_ip', models.GenericIPAddressField()),
                ('response_domain', models.CharField(max_length=255)),
                ('response_status', models.CharField(max_length=10)),
                ('response_time', models.FloatField()),
                ('additional_info', models.IntegerField()),
                ('query_size', models.IntegerField()),
            ],
        ),
    ]
