# Generated by Django 5.0 on 2023-12-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dnslog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnslog',
            old_name='timestamp',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='dnslog',
            old_name='query_domain',
            new_name='domain_name',
        ),
        migrations.RenameField(
            model_name='dnslog',
            old_name='query_ip',
            new_name='ip_address',
        ),
        migrations.RenameField(
            model_name='dnslog',
            old_name='additional_info',
            new_name='num_records',
        ),
        migrations.RenameField(
            model_name='dnslog',
            old_name='response_domain',
            new_name='process_name',
        ),
        migrations.RenameField(
            model_name='dnslog',
            old_name='response_status',
            new_name='query_class',
        ),
        migrations.RenameField(
            model_name='dnslog',
            old_name='response_time',
            new_name='query_time',
        ),
        migrations.RenameField(
            model_name='dnslog',
            old_name='query_size',
            new_name='record_size',
        ),
        migrations.RemoveField(
            model_name='dnslog',
            name='process',
        ),
        migrations.RemoveField(
            model_name='dnslog',
            name='response_ip',
        ),
        migrations.AddField(
            model_name='dnslog',
            name='query_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnslog',
            name='record_type',
            field=models.CharField(max_length=10),
        ),
    ]
