# Generated by Django 5.0 on 2023-12-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_doamin_query_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='country',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='country',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
