# Generated by Django 5.0 on 2023-12-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_timestamp_dnslog_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnslog',
            name='process_name',
        ),
    ]
