# Generated by Django 5.0 on 2023-12-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_query_country_reply_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
