# Generated by Django 5.0 on 2023-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_log_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaincount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domains', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('count', models.IntegerField(max_length=100)),
            ],
        ),
    ]
