# Generated by Django 5.0 on 2023-12-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_dnslog_process_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ParsedPacket',
        ),
    ]
