# Generated by Django 5.0 on 2023-12-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blacklist_delete_parsedpacket'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnslog',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
