# Generated by Django 5.0 on 2023-12-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_threatintel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatintel',
            name='domain',
        ),
        migrations.AddField(
            model_name='threatintel',
            name='indicator',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threatintel',
            name='threat_level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
