# Generated by Django 5.0 on 2023-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_domaincount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaincount',
            name='count',
            field=models.IntegerField(),
        ),
    ]
