# Generated by Django 5.0 on 2023-12-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dnslog_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnslog',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
