# Generated by Django 5.0 on 2023-12-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_domaincount_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaincount',
            name='count',
            field=models.IntegerField(blank=0, default=0),
        ),
    ]
