# Generated by Django 5.0 on 2023-12-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_domaincount_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domaincount',
            name='client',
        ),
    ]
