# Generated by Django 5.0 on 2023-12-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_dnslog_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delay',
        ),
        migrations.DeleteModel(
            name='Domaincount',
        ),
        migrations.RemoveField(
            model_name='log',
            name='query',
        ),
        migrations.RemoveField(
            model_name='log',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
