# Generated by Django 5.0 on 2023-12-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_log_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domaincount',
            old_name='domains',
            new_name='domain',
        ),
    ]
