# Generated by Django 5.0 on 2023-12-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_domains_domaincount_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ParsedPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('src', models.GenericIPAddressField(blank=True, null=True)),
                ('dst', models.GenericIPAddressField(blank=True, null=True)),
                ('proto', models.CharField(max_length=255)),
                ('len', models.IntegerField()),
                ('sport', models.IntegerField(blank=True, null=True)),
                ('dport', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
